# Generated by Django 5.2.5 on 2025-10-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-start_date']},
        ),
    ]
