# Generated by Django 5.2.5 on 2025-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('weightlifting', 'Weightlifting'), ('yoga', 'Yoga'), ('hiking', 'Hiking'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(),
        ),
    ]
