# Generated by Django 5.2.5 on 2025-10-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_goal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
